/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as homeIndexRouteImport } from './routes/(home)/index'
import { Route as homeAboutRouteImport } from './routes/(home)/about'
import { Route as dashboardDashboardRouteImport } from './routes/(dashboard)/dashboard'
import { Route as authLoginRouteRouteImport } from './routes/(auth)/login/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as homePaintingsPaintingIdRouteImport } from './routes/(home)/paintings.$paintingId'
import { Route as dashboardDashboardPaintingsRouteImport } from './routes/(dashboard)/dashboard_.paintings'

const homeIndexRoute = homeIndexRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const homeAboutRoute = homeAboutRouteImport.update({
  id: '/(home)/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardDashboardRoute = dashboardDashboardRouteImport.update({
  id: '/(dashboard)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRouteRoute = authLoginRouteRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const homePaintingsPaintingIdRoute = homePaintingsPaintingIdRouteImport.update({
  id: '/(home)/paintings/$paintingId',
  path: '/paintings/$paintingId',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardDashboardPaintingsRoute =
  dashboardDashboardPaintingsRouteImport.update({
    id: '/(dashboard)/dashboard_/paintings',
    path: '/dashboard/paintings',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof authLoginRouteRoute
  '/dashboard': typeof dashboardDashboardRoute
  '/about': typeof homeAboutRoute
  '/': typeof homeIndexRoute
  '/dashboard/paintings': typeof dashboardDashboardPaintingsRoute
  '/paintings/$paintingId': typeof homePaintingsPaintingIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/login': typeof authLoginRouteRoute
  '/dashboard': typeof dashboardDashboardRoute
  '/about': typeof homeAboutRoute
  '/': typeof homeIndexRoute
  '/dashboard/paintings': typeof dashboardDashboardPaintingsRoute
  '/paintings/$paintingId': typeof homePaintingsPaintingIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)/login': typeof authLoginRouteRoute
  '/(dashboard)/dashboard': typeof dashboardDashboardRoute
  '/(home)/about': typeof homeAboutRoute
  '/(home)/': typeof homeIndexRoute
  '/(dashboard)/dashboard_/paintings': typeof dashboardDashboardPaintingsRoute
  '/(home)/paintings/$paintingId': typeof homePaintingsPaintingIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/dashboard'
    | '/about'
    | '/'
    | '/dashboard/paintings'
    | '/paintings/$paintingId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/dashboard'
    | '/about'
    | '/'
    | '/dashboard/paintings'
    | '/paintings/$paintingId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/(auth)/login'
    | '/(dashboard)/dashboard'
    | '/(home)/about'
    | '/(home)/'
    | '/(dashboard)/dashboard_/paintings'
    | '/(home)/paintings/$paintingId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authLoginRouteRoute: typeof authLoginRouteRoute
  dashboardDashboardRoute: typeof dashboardDashboardRoute
  homeAboutRoute: typeof homeAboutRoute
  homeIndexRoute: typeof homeIndexRoute
  dashboardDashboardPaintingsRoute: typeof dashboardDashboardPaintingsRoute
  homePaintingsPaintingIdRoute: typeof homePaintingsPaintingIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/about': {
      id: '/(home)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof homeAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/dashboard': {
      id: '/(dashboard)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof dashboardDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/paintings/$paintingId': {
      id: '/(home)/paintings/$paintingId'
      path: '/paintings/$paintingId'
      fullPath: '/paintings/$paintingId'
      preLoaderRoute: typeof homePaintingsPaintingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/dashboard_/paintings': {
      id: '/(dashboard)/dashboard_/paintings'
      path: '/dashboard/paintings'
      fullPath: '/dashboard/paintings'
      preLoaderRoute: typeof dashboardDashboardPaintingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  authLoginRouteRoute: authLoginRouteRoute,
  dashboardDashboardRoute: dashboardDashboardRoute,
  homeAboutRoute: homeAboutRoute,
  homeIndexRoute: homeIndexRoute,
  dashboardDashboardPaintingsRoute: dashboardDashboardPaintingsRoute,
  homePaintingsPaintingIdRoute: homePaintingsPaintingIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
